version: "3.8"

services:
  crawl4ai-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      # Optional: Mount for development (comment out for production)
      # - ./app.py:/app/app.py
      # - ./crawl.py:/app/crawl.py
      - /dev/shm:/dev/shm # Shared memory for Chrome
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security options for Chrome in container
    security_opt:
      - seccomp:unconfined
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
